# This Playbook build a simple Docker image, to test the good installation 
# of the Docker environment.

- hosts: build
  gather_facts: no
  become: yes #become sudo
  become_method: sudo #become sudo
  tasks:

    - include_vars:
        file: image_var.yaml

    - name: create build directory
      file:
        path: "/tmp/{{image_name}}"
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: copy Dockerfile
      copy:
        src: ./Dockerfile
        dest: "/tmp/{{image_name}}/Dockerfile"
        owner: root
        group: root
        mode: '0644'

    - name: build container image
      docker_image:
        name: "{{image_name}}:{{image_version}}"
        source: build
        build:
          path: "/tmp/{{image_name}}"
        state: present