- hosts: build
  become: yes #become sudo
  become_method: sudo #become sudo
  gather_facts: no
  tasks:
  
    - include_vars:
        file: image_var.yaml

    - name: copy tarball to host
      copy:
        src: "./image/{{image_name}}_{{image_version}}.tar"
        dest: "/tmp/{{image_name}}/{{image_name}}_{{image_version}}.tar"

    - name: load container from tarball
      docker_image:
        name: "{{image_name}}:{{image_version}}"
        load_path: "/tmp/{{image_name}}/{{image_name}}_{{image_version}}.tar"
        state: present
        source: load